early unit test (not working)
collinarnett/PersonalGamification pull request #30
Opened 2022-04-26 06:05 UTC by justinsriver

Added some string methods for each class. Currently having an error with the Outcome class, I can't call the reward method and also in org.scalatest._ there already exists an object called Outcome so I changed ours to Outcome1 for this commit and will need to talk about it with the group.

2022-04-26 15:46 UTC, collinarnett requested changes
We also don't need to test functionality related to parsing since that's the job of scopt.

2022-04-26 15:46 UTC, collinarnett commented on src/test/scala/Tests.scala
> +    val statuses = Seq(status)
There should be tests for Sequences of 0, 1 or many and combinations of these three states for items and status affects.

2022-04-26 15:46 UTC, collinarnett commented on src/main/scala/StatusEffect.scala
> +      |""".stripMargin
Not in the scope of unit tests.

2022-04-26 15:46 UTC, collinarnett commented on src/main/scala/Task.scala
> +    |""".stripMargin
Not in the scope of unit tests.

2022-04-26 15:46 UTC, collinarnett commented on src/test/scala/Tests.scala
> +import javax.lang.model.`type`.ErrorType
Why do we need this? How does it work?

2022-04-29 05:16 UTC, justinsriver commented
Removed the string methods, Removed unnecessary imports, and added actual Unit tests that test the reward and punishment functions.

2022-04-29 20:38 UTC, collinarnett requested changes
The goal of these tests should be to break the program. There are cases that are not tested for. Please review the codebase and make cases designed to cover every scenario.

2022-04-29 20:38 UTC, collinarnett commented on src/test/scala/Tests.scala
> +  val cal = Calendar.getInstance()
All lifetimes are the same. This means that anything testing whether or not things have expired will all have the same result.

2022-04-29 20:38 UTC, collinarnett commented on src/test/scala/Tests.scala
> +  val r = scala.util.Random
Random number generator needs a seed, otherwise the tests will have different outcomes each time you run them.

2022-04-29 20:38 UTC, collinarnett commented on src/test/scala/Tests.scala
> +  val status3 = StatusEffect(name="Nerd", description="Maidenless", affect= -9, lifetime=cal)
No zero case for effect.

2022-04-29 20:38 UTC, collinarnett commented on src/test/scala/Tests.scala
> +  val itm3 = Item(name="Lance", description="Pokes things", affect=4, lifetime=cal)
No case for zero.

2022-05-01 06:27 UTC, collinarnett approved these changes

2022-05-01 06:27 UTC, merged